team_color: "blue"
my_cars: ["robot_blue", "robot_blue2"]
# my_cars: ["robot_blue"] #"robot_blue2"
loop_hz: 0.2
state_timeout_s: 8.0
default_patrol_points:
  - [-0.5, 0.0]
  - [-1.0, -1.0]
  - [0.0, -1.2]
llm:
<<<<<<< HEAD
  enabled: false
  service_url: "http://127.0.0.1:8001/plan"
  timeout_s: 60
=======
  enabled: true
  service_url: "http://127.0.0.1:8002/plan"
  timeout_s: 30
>>>>>>> 8f988c3925acf6e07128c5d0367f6d15fb7d5b68
