team_color: "red"
my_cars: ["robot_red", "robot_red2"]
# my_cars: ["robot_red"] #"robot_red2"
loop_hz: 0.2
state_timeout_s: 8.0
default_patrol_points:
  - [1.0, 1.0]
  - [0.5, 0.0]
  - [0.0, 1.2]
llm:
  enabled: true
  service_url: "http://127.0.0.1:8001/plan"
  timeout_s: 30